'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class employee
    Public Property employeeID As Integer
    Public Property employee_name As String
    Public Property employee_surname As String
    Public Property username As String
    Public Property password As String
    Public Property salt As String
    Public Property passcode As String

End Class
