'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class member
    Public Property memberID As Integer
    Public Property firstName As String
    Public Property lastName As String
    Public Property city As String
    Public Property zip As String
    Public Property street As String
    Public Property number As String
    Public Property email As String
    Public Property currentlyHiring As Nullable(Of SByte)
    Public Property balance As Nullable(Of Decimal)
    Public Property picture As Byte()

    Public Overridable Property rentals As ICollection(Of rental) = New HashSet(Of rental)
    Public Overridable Property payments As ICollection(Of payment) = New HashSet(Of payment)

End Class
