'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class movie_copies
    Public Property CopyID As Integer
    Public Property movieID As Integer
    Public Property condition As String
    Public Property comments As String

    Public Overridable Property movy As movy

End Class
