'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class movy
    Public Property movieID As Integer
    Public Property title As String
    Public Property year As Nullable(Of Short)
    Public Property language As String
    Public Property country As String
    Public Property availableCopies As Nullable(Of Integer)
    Public Property oscar As String
    Public Property genre As String
    Public Property rentalRate As Decimal
    Public Property penalty As Nullable(Of Decimal)
    Public Property category As String

    Public Overridable Property movie_copies As ICollection(Of movie_copies) = New HashSet(Of movie_copies)

End Class
