'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rate
    Public Property rateId As Integer
    Public Property Hot As Nullable(Of Integer)
    Public Property Medium As Nullable(Of Integer)
    Public Property Low As Nullable(Of Integer)

End Class
