'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class renting_cost
    Public Property costId As Integer
    Public Property Hot As Integer
    Public Property Medium As Integer
    Public Property Low As Integer
    Public Property [date] As Date

End Class
