'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class video_dbEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=video_dbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property category_tb() As DbSet(Of category_tb)
    Public Property employees() As DbSet(Of employee)
    Public Property members() As DbSet(Of member)
    Public Property movie_copies() As DbSet(Of movie_copies)
    Public Property movies() As DbSet(Of movy)
    Public Property payments() As DbSet(Of payment)
    Public Property penalty_cost() As DbSet(Of penalty_cost)
    Public Property rates() As DbSet(Of rate)
    Public Property rentals() As DbSet(Of rental)
    Public Property renting_cost() As DbSet(Of renting_cost)
    Public Property cover_images() As DbSet(Of cover_images)

    Public Overridable Function ChangeCategory(id As Nullable(Of Integer), colName As String) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Integer)))

        Dim colNameParameter As ObjectParameter = If(colName IsNot Nothing, New ObjectParameter("colName", colName), New ObjectParameter("colName", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ChangeCategory", idParameter, colNameParameter)
    End Function

End Class
